version: '3.8'

services:
  orasul-meu-db:
    restart: always
    image: postgis/postgis:15-3.3
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    command: -p $DB_PORT
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  orasul-meu-server:
    image: node:18.16.0-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:debug
    working_dir:
      /usr/app
    volumes:
      - .:/usr/app/
    ports:
      - $PORT:$PORT
      - 9229:9229 # debug
    depends_on:
      - orasul-meu-db
    env_file:
      - .env

