version: '3.8'

services:
  orasul-meu-server:
    image: node:18.16.0-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:debug
    working_dir:
      /usr/app
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - $PORT:$PORT
      - 9229:9229 # debug
    env_file:
      - .env

