version: '3.8'

services:
  db:
    restart: always
    image: postgis/postgis:15-3.3
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    command: -p $DB_PORT
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    image: node:18.16.0-alpine3.17
    build: .
    command: npm run start:docker
    working_dir:
      /usr/app
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - $PORT:$PORT
      - 9229:9229 # debug
    depends_on:
      - db
    env_file:
      - .env.docker

