/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thenoughtfox.orasulmeu.net.model.media


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param files1 
 */


data class MediaDto (

    @SerializedName("files1")
    val files1: kotlin.collections.List<java.io.File>

)

