name: Android Build

on:
    pull_request:
      paths:
        - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'  
          java-version: 17

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install OpenAPI Generator CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Generate API Client
        run: ./scripts/generateApiClients shared/swagger-spec.yaml android/generated/api

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: android

      - name: Run Tests                   
        run: ./gradlew test
        working-directory: android

      - name: Build Project              
        run: ./gradlew assemble
        working-directory: android