name: Android Build

on:
    pull_request:
      paths:
        - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'  
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Run Tests                   
        run: android/gradlew test

      - name: Build Project              
        run: android/gradlew assemble