name: Android Build

on:
    pull_request:
      paths:
        - 'android/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'  
          java-version: 17

      - name: Grant execute permissions for gradlew //this step is only for macOS
        run: chmod +x ./gradlew 

      - name: Run Tests                   
        run: ./gradlew test

      - name: Build Project              
        run: ./gradlew assemble